require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

# desc "Greet the user"
# task :greet do
#   puts "HI"
# end

# task(:greet) do
#   puts "HI"
# end
